language: r
pandoc_version: 1.19.2.1
sudo: false
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
before_install:
- sudo apt-get -qq update
- sudo apt-get install libmagick++-dev
- sudo apt-get install --only-upgrade imagemagick
before_script:
- chmod +x ./_build_and_deploy.sh
- git config --global user.email "christoph.molnar@gmail.com"
- git config --global user.name "Christoph Molnar"
script: ./_build_and_deploy.sh
r_github_packages: christophM/iml
env:
  global:
  - secure: jmo/WiDp6XfW5zU7e9yZuktt74+5WlzqKtXv3Tq14LUdDNuQfopPAvobjh6/ZVIcxA+lsfGt6G2lDMsKBsKuVOK0rrk99WmAt0UWEvS16ftoldFs3U3xHZI9YXmd1iBT5h4b5GNL25woGHfxyHw87dQkacatAbXH7b8D24ALRNvx1UAGVW4Dz/D52xvgL6Lncu296SrGA9PqXmiHuq679p7j7V90+z5KK9XxI1PcYNRKhMdtQkswa4132GM42tBQ8OoU4v2aWBgBEtSO8J6KXO/B1j184c0aSU2qoooxFCN0ZeR+ECs418wDj7wj98VfQDFCUOCteVmLSvLHgct2t70F5bNPbn+7PD+cwz4HPEy7zJffHxjKepsiLZEWUkGoQ6cSYEUUOicAOL0lrQtLxA14Yz/Y569Iq6/TrxL+FDYXBmJkwZ5gBffEbmGfmubkUZLNBfh+n65VYl71tGWM9e8tYBPLq1G0c+2cbN4E9H/A3wo7sP4JjKHmUVvZjqAOfxuuFpXua6wPSa6AyuuvjKfDzJOYjro6CWO4KYjUZ6qZ9DEt+xVrv39KMUviVTZPnUzc8kmz0zFDFnvJeOo/AGZ8ackDK6C3UJmpCAUxkdqFywHcAdl5vhoF4o5kk5Ucsa9Yn+SfNAe3jOicEV1M5U8yZ4vr/xUJTS0E/opkQMc=
