language: r
pandoc_version: 1.18

sudo: false

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script: ./_deploy.sh
